# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Scythe
      run: cd cmd/ && env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o Scythe

  test:
    name: Test user flags
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test NetCat Help Menu
      run: echo "Add your go tests when ready"
    #   run: cd cmd && ./Scythe Netcat -h

    # - name: Test File Transfer Help Menu
    #   run: cd cmd && ./Scythe FileTransfer -h
